### ISSUE TITLE
functions with "Section: " declarations in docstring appear in "Uncategorized forms"

### ISSUE THREAD

**Issue by gpwclark** [sstanfield/slsh#37]
functions with "Section: " declarations in docstring appear in "Uncategorized forms"

here: https://sstanfield.github.io/slsh/

**Comment by sstanfield** [comment]
The excess "Uncategorized forms" were being caused by a few issues that crept into sl-sh itself.  I fixed all of them tonight and the docs are fine again.  We might want to have CI fail if docs find any of these in the future- one main problem was a regression in ns-import (was no longer leaving the docstrings intact) so having CI fail early might be good.  Otherwise you can close this unless you had something you think needs doing.
